version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
  - package-ecosystem: "dockerfile"
    directory: "/"
    schedule:
      interval: "weekly"
