name: Build & Push Artifacts

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      IMAGE_HASH:
        value: ${{ jobs.build_push_image.outputs.IMAGE_HASH }}

permissions:
  contents: read
  id-token: write

jobs:
  build_push_image:
    name: Build Image
    runs-on: ubuntu-latest
    outputs:
      IMAGE_HASH: ${{ steps.build-push-image.outputs.IMAGE_HASH }}
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
        role-session-name: "GitHubActions"
        aws-region: eu-west-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-push-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fidel-ecr
        IMAGE_HASH: ${{ hashFiles('service/**', 'Dockerfile') }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_HASH .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_HASH
        echo "::set-output name=IMAGE_HASH::$IMAGE_HASH"
