name: integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install -r tests/requirements.txt
        pytest
    - name: Terraform Format
      run: terraform fmt -check -recursive -diff
