name: integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd service
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install -r tests/requirements.txt
        pytest
    - name: Terraform Format
      run: terraform fmt -check -recursive -diff

  tflint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v1

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --module --enable-rule terraform_unused_declarations --enable-rule terraform_naming_convention -f compact
