name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  workflow_dispatch:
  workflow_call:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r service/requirements.txt
        pip install -r tests/requirements.txt
    - name: Test with pytest
      run: pytest
